//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermInfo
{
    public static class TermInfoCaps
    {
        public enum Boolean
        {
            /// <summary>
            /// The auto_left_margin [auto_left_margin, bw] bool capability indicates cub 1 wraps from column 0 to last column.
            /// </summary>
            AutoLeftMargin = 0,

            /// <summary>
            /// The auto_right_margin [auto_right_margin, am] bool capability indicates terminal has automatic margins.
            /// </summary>
            AutoRightMargin = 1,

            /// <summary>
            /// The no_esc_ctlc [no_esc_ctlc, xsb] bool capability indicates beehive f 1 escape f 2 ctrl c.
            /// </summary>
            NoEscCtlc = 2,

            /// <summary>
            /// The ceol_standout_glitch [ceol_standout_glitch, xhp] bool capability indicates standout not erased by overwriting hp.
            /// </summary>
            CeolStandoutGlitch = 3,

            /// <summary>
            /// The eat_newline_glitch [eat_newline_glitch, xenl] bool capability indicates newline ignored after 80 cols concept.
            /// </summary>
            EatNewlineGlitch = 4,

            /// <summary>
            /// The erase_overstrike [erase_overstrike, eo] bool capability indicates can erase overstrikes with a blank.
            /// </summary>
            EraseOverstrike = 5,

            /// <summary>
            /// The generic_type [generic_type, gn] bool capability indicates generic line type.
            /// </summary>
            GenericType = 6,

            /// <summary>
            /// The hard_copy [hard_copy, hc] bool capability indicates hardcopy terminal.
            /// </summary>
            HardCopy = 7,

            /// <summary>
            /// The has_meta_key [has_meta_key, km] bool capability indicates has a meta key (i.e., sets 8th bit).
            /// </summary>
            HasMetaKey = 8,

            /// <summary>
            /// The has_status_line [has_status_line, hs] bool capability indicates has extra status line.
            /// </summary>
            HasStatusLine = 9,

            /// <summary>
            /// The insert_null_glitch [insert_null_glitch, in] bool capability indicates insert mode distinguishes nulls.
            /// </summary>
            InsertNullGlitch = 10,

            /// <summary>
            /// The memory_above [memory_above, da] bool capability indicates display may be retained above the screen.
            /// </summary>
            MemoryAbove = 11,

            /// <summary>
            /// The memory_below [memory_below, db] bool capability indicates display may be retained below the screen.
            /// </summary>
            MemoryBelow = 12,

            /// <summary>
            /// The move_insert_mode [move_insert_mode, mir] bool capability indicates safe to move while in insert mode.
            /// </summary>
            MoveInsertMode = 13,

            /// <summary>
            /// The move_standout_mode [move_standout_mode, msgr] bool capability indicates safe to move while in standout mode.
            /// </summary>
            MoveStandoutMode = 14,

            /// <summary>
            /// The over_strike [over_strike, os] bool capability indicates terminal can overstrike.
            /// </summary>
            OverStrike = 15,

            /// <summary>
            /// The status_line_esc_ok [status_line_esc_ok, eslok] bool capability indicates escape can be used on the status line.
            /// </summary>
            StatusLineEscOk = 16,

            /// <summary>
            /// The dest_tabs_magic_smso [dest_tabs_magic_smso, xt] bool capability indicates tabs destructive magic so char t 1061.
            /// </summary>
            DestTabsMagicSmso = 17,

            /// <summary>
            /// The tilde_glitch [tilde_glitch, hz] bool capability indicates cannot print s hazeltine.
            /// </summary>
            TildeGlitch = 18,

            /// <summary>
            /// The transparent_underline [transparent_underline, ul] bool capability indicates underline character overstrikes.
            /// </summary>
            TransparentUnderline = 19,

            /// <summary>
            /// The xon_xoff [xon_xoff, xon] bool capability indicates terminal uses xon xoff handshaking.
            /// </summary>
            XonXoff = 20,

            /// <summary>
            /// The needs_xon_xoff [needs_xon_xoff, nxon] bool capability indicates padding will not work xon xoff required.
            /// </summary>
            NeedsXonXoff = 21,

            /// <summary>
            /// The prtr_silent [prtr_silent, mc5i] bool capability indicates printer will not echo on screen.
            /// </summary>
            PrtrSilent = 22,

            /// <summary>
            /// The hard_cursor [hard_cursor, chts] bool capability indicates cursor is hard to see.
            /// </summary>
            HardCursor = 23,

            /// <summary>
            /// The non_rev_rmcup [non_rev_rmcup, nrrmc] bool capability indicates smcup does not reverse rmcup.
            /// </summary>
            NonRevRmcup = 24,

            /// <summary>
            /// The no_pad_char [no_pad_char, npc] bool capability indicates pad character does not exist.
            /// </summary>
            NoPadChar = 25,

            /// <summary>
            /// The non_dest_scroll_region [non_dest_scroll_region, ndscr] bool capability indicates scrolling region is non destructive.
            /// </summary>
            NonDestScrollRegion = 26,

            /// <summary>
            /// The can_change [can_change, ccc] bool capability indicates terminal can re define existing colors.
            /// </summary>
            CanChange = 27,

            /// <summary>
            /// The back_color_erase [back_color_erase, bce] bool capability indicates screen erased with background color.
            /// </summary>
            BackColorErase = 28,

            /// <summary>
            /// The hue_lightness_saturation [hue_lightness_saturation, hls] bool capability indicates terminal uses only hls color notation tektronix.
            /// </summary>
            HueLightnessSaturation = 29,

            /// <summary>
            /// The col_addr_glitch [col_addr_glitch, xhpa] bool capability indicates only positive motion for hpa mhpa caps.
            /// </summary>
            ColAddrGlitch = 30,

            /// <summary>
            /// The cr_cancels_micro_mode [cr_cancels_micro_mode, crxm] bool capability indicates using cr turns off micro mode.
            /// </summary>
            CrCancelsMicroMode = 31,

            /// <summary>
            /// The has_print_wheel [has_print_wheel, daisy] bool capability indicates printer needs operator to change character set.
            /// </summary>
            HasPrintWheel = 32,

            /// <summary>
            /// The row_addr_glitch [row_addr_glitch, xvpa] bool capability indicates only positive motion for vpa mvpa caps.
            /// </summary>
            RowAddrGlitch = 33,

            /// <summary>
            /// The semi_auto_right_margin [semi_auto_right_margin, sam] bool capability indicates printing in last column causes cr.
            /// </summary>
            SemiAutoRightMargin = 34,

            /// <summary>
            /// The cpi_changes_res [cpi_changes_res, cpix] bool capability indicates changing character pitch changes resolution.
            /// </summary>
            CpiChangesRes = 35,

            /// <summary>
            /// The lpi_changes_res [lpi_changes_res, lpix] bool capability indicates changing line pitch changes resolution.
            /// </summary>
            LpiChangesRes = 36,

            /// <summary>
            /// The backspaces_with_bs [backspaces_with_bs, OTbs] bool capability indicates uses h to move left.
            /// </summary>
            BackspacesWithBs = 37,

            /// <summary>
            /// The crt_no_scrolling [crt_no_scrolling, OTns] bool capability indicates crt cannot scroll.
            /// </summary>
            CrtNoScrolling = 38,

            /// <summary>
            /// The no_correctly_working_cr [no_correctly_working_cr, OTnc] bool capability indicates no way to go to start of line.
            /// </summary>
            NoCorrectlyWorkingCr = 39,

            /// <summary>
            /// The gnu_has_meta_key [gnu_has_meta_key, OTMT] bool capability indicates has meta key.
            /// </summary>
            GnuHasMetaKey = 40,

            /// <summary>
            /// The linefeed_is_newline [linefeed_is_newline, OTNL] bool capability indicates move down with n.
            /// </summary>
            LinefeedIsNewline = 41,

            /// <summary>
            /// The has_hardware_tabs [has_hardware_tabs, OTpt] bool capability indicates has 8 char tabs invoked with ^i.
            /// </summary>
            HasHardwareTabs = 42,

            /// <summary>
            /// The return_does_clr_eol [return_does_clr_eol, OTxr] bool capability indicates return clears the line.
            /// </summary>
            ReturnDoesClrEol = 43,
        }

        public enum Num
        {
            /// <summary>
            /// The columns [columns, cols] num capability is number of columns in a line.
            /// </summary>
            Columns = 0,

            /// <summary>
            /// The init_tabs [init_tabs, it] num capability is tabs initially every spaces.
            /// </summary>
            InitTabs = 1,

            /// <summary>
            /// The lines [lines, lines] num capability is number of lines on screen or page.
            /// </summary>
            Lines = 2,

            /// <summary>
            /// The lines_of_memory [lines_of_memory, lm] num capability is lines of memory if line 0 means varies.
            /// </summary>
            LinesOfMemory = 3,

            /// <summary>
            /// The magic_cookie_glitch [magic_cookie_glitch, xmc] num capability is number of blank characters left by smso or rmso.
            /// </summary>
            MagicCookieGlitch = 4,

            /// <summary>
            /// The padding_baud_rate [padding_baud_rate, pb] num capability is lowest baud rate where padding needed.
            /// </summary>
            PaddingBaudRate = 5,

            /// <summary>
            /// The virtual_terminal [virtual_terminal, vt] num capability is virtual terminal number cb unix.
            /// </summary>
            VirtualTerminal = 6,

            /// <summary>
            /// The width_status_line [width_status_line, wsl] num capability is number of columns in status line.
            /// </summary>
            WidthStatusLine = 7,

            /// <summary>
            /// The num_labels [num_labels, nlab] num capability is number of labels on screen.
            /// </summary>
            NumLabels = 8,

            /// <summary>
            /// The label_height [label_height, lh] num capability is rows in each label.
            /// </summary>
            LabelHeight = 9,

            /// <summary>
            /// The label_width [label_width, lw] num capability is columns in each label.
            /// </summary>
            LabelWidth = 10,

            /// <summary>
            /// The max_attributes [max_attributes, ma] num capability is maximum combined attributes terminal can handle.
            /// </summary>
            MaxAttributes = 11,

            /// <summary>
            /// The maximum_windows [maximum_windows, wnum] num capability is maximum number of definable windows.
            /// </summary>
            MaximumWindows = 12,

            /// <summary>
            /// The max_colors [max_colors, colors] num capability is maximum number of colors on screen.
            /// </summary>
            MaxColors = 13,

            /// <summary>
            /// The max_pairs [max_pairs, pairs] num capability is maximum number of color pairs on the screen.
            /// </summary>
            MaxPairs = 14,

            /// <summary>
            /// The no_color_video [no_color_video, ncv] num capability is video attributes that cannot be used with colors.
            /// </summary>
            NoColorVideo = 15,

            /// <summary>
            /// The buffer_capacity [buffer_capacity, bufsz] num capability is numbers of bytes buffered before printing.
            /// </summary>
            BufferCapacity = 16,

            /// <summary>
            /// The dot_vert_spacing [dot_vert_spacing, spinv] num capability is spacing of pins vertically in pins per inch.
            /// </summary>
            DotVertSpacing = 17,

            /// <summary>
            /// The dot_horz_spacing [dot_horz_spacing, spinh] num capability is spacing of dots horizontally in dots per inch.
            /// </summary>
            DotHorzSpacing = 18,

            /// <summary>
            /// The max_micro_address [max_micro_address, maddr] num capability is maximum value in micro ... address.
            /// </summary>
            MaxMicroAddress = 19,

            /// <summary>
            /// The max_micro_jump [max_micro_jump, mjump] num capability is maximum value in parm ... micro.
            /// </summary>
            MaxMicroJump = 20,

            /// <summary>
            /// The micro_col_size [micro_col_size, mcs] num capability is character step size when in micro mode.
            /// </summary>
            MicroColSize = 21,

            /// <summary>
            /// The micro_line_size [micro_line_size, mls] num capability is line step size when in micro mode.
            /// </summary>
            MicroLineSize = 22,

            /// <summary>
            /// The number_of_pins [number_of_pins, npins] num capability is numbers of pins in print head.
            /// </summary>
            NumberOfPins = 23,

            /// <summary>
            /// The output_res_char [output_res_char, orc] num capability is horizontal resolution in units per line.
            /// </summary>
            OutputResChar = 24,

            /// <summary>
            /// The output_res_line [output_res_line, orl] num capability is vertical resolution in units per line.
            /// </summary>
            OutputResLine = 25,

            /// <summary>
            /// The output_res_horz_inch [output_res_horz_inch, orhi] num capability is horizontal resolution in units per inch.
            /// </summary>
            OutputResHorzInch = 26,

            /// <summary>
            /// The output_res_vert_inch [output_res_vert_inch, orvi] num capability is vertical resolution in units per inch.
            /// </summary>
            OutputResVertInch = 27,

            /// <summary>
            /// The print_rate [print_rate, cps] num capability is print rate in characters per second.
            /// </summary>
            PrintRate = 28,

            /// <summary>
            /// The wide_char_size [wide_char_size, widcs] num capability is character step size when in double wide mode.
            /// </summary>
            WideCharSize = 29,

            /// <summary>
            /// The buttons [buttons, btns] num capability is number of buttons on mouse.
            /// </summary>
            Buttons = 30,

            /// <summary>
            /// The bit_image_entwining [bit_image_entwining, bitwin] num capability is number of passes for each bit image row.
            /// </summary>
            BitImageEntwining = 31,

            /// <summary>
            /// The bit_image_type [bit_image_type, bitype] num capability is type of bit image device.
            /// </summary>
            BitImageType = 32,

            /// <summary>
            /// The magic_cookie_glitch_ul [magic_cookie_glitch_ul, OTug] num capability is number of blanks left by ul.
            /// </summary>
            MagicCookieGlitchUl = 33,

            /// <summary>
            /// The carriage_return_delay [carriage_return_delay, OTdC] num capability is pad needed for cr.
            /// </summary>
            CarriageReturnDelay = 34,

            /// <summary>
            /// The new_line_delay [new_line_delay, OTdN] num capability is pad needed for lf.
            /// </summary>
            NewLineDelay = 35,

            /// <summary>
            /// The backspace_delay [backspace_delay, OTdB] num capability is padding required for h.
            /// </summary>
            BackspaceDelay = 36,

            /// <summary>
            /// The horizontal_tab_delay [horizontal_tab_delay, OTdT] num capability is padding required for i.
            /// </summary>
            HorizontalTabDelay = 37,

            /// <summary>
            /// The number_of_function_keys [number_of_function_keys, OTkn] num capability is count of function keys.
            /// </summary>
            NumberOfFunctionKeys = 38,
        }

        public enum String
        {
            /// <summary>
            /// The back_tab [back_tab, cbt] string capability is the back tab p.
            /// </summary>
            BackTab = 0,

            /// <summary>
            /// The bell [bell, bel] string capability is the audible signal bell p.
            /// </summary>
            Bell = 1,

            /// <summary>
            /// The carriage_return [carriage_return, cr] string capability is the carriage return p p.
            /// </summary>
            CarriageReturn = 2,

            /// <summary>
            /// The change_scroll_region [change_scroll_region, csr] string capability is the change region to line 1 to line 2 p.
            /// </summary>
            ChangeScrollRegion = 3,

            /// <summary>
            /// The clear_all_tabs [clear_all_tabs, tbc] string capability is the clear all tab stops p.
            /// </summary>
            ClearAllTabs = 4,

            /// <summary>
            /// The clear_screen [clear_screen, clear] string capability is the clear screen and home cursor p.
            /// </summary>
            ClearScreen = 5,

            /// <summary>
            /// The clr_eol [clr_eol, el] string capability is the clear to end of line p.
            /// </summary>
            ClrEol = 6,

            /// <summary>
            /// The clr_eos [clr_eos, ed] string capability is the clear to end of screen p.
            /// </summary>
            ClrEos = 7,

            /// <summary>
            /// The column_address [column_address, hpa] string capability is the horizontal position 1 absolute p.
            /// </summary>
            ColumnAddress = 8,

            /// <summary>
            /// The command_character [command_character, cmdch] string capability is the terminal settable cmd character in prototype.
            /// </summary>
            CommandCharacter = 9,

            /// <summary>
            /// The cursor_address [cursor_address, cup] string capability is the move to row 1 columns 2.
            /// </summary>
            CursorAddress = 10,

            /// <summary>
            /// The cursor_down [cursor_down, cud1] string capability is the down one line.
            /// </summary>
            CursorDown = 11,

            /// <summary>
            /// The cursor_home [cursor_home, home] string capability is the home cursor if no cup.
            /// </summary>
            CursorHome = 12,

            /// <summary>
            /// The cursor_invisible [cursor_invisible, civis] string capability is the make cursor invisible.
            /// </summary>
            CursorInvisible = 13,

            /// <summary>
            /// The cursor_left [cursor_left, cub1] string capability is the move left one space.
            /// </summary>
            CursorLeft = 14,

            /// <summary>
            /// The cursor_mem_address [cursor_mem_address, mrcup] string capability is the memory relative cursor addressing move to row 1 columns 2.
            /// </summary>
            CursorMemAddress = 15,

            /// <summary>
            /// The cursor_normal [cursor_normal, cnorm] string capability is the make cursor appear normal undo civis cvvis.
            /// </summary>
            CursorNormal = 16,

            /// <summary>
            /// The cursor_right [cursor_right, cuf1] string capability is the non destructive space (move right one space).
            /// </summary>
            CursorRight = 17,

            /// <summary>
            /// The cursor_to_ll [cursor_to_ll, ll] string capability is the last line first column if no cup.
            /// </summary>
            CursorToLl = 18,

            /// <summary>
            /// The cursor_up [cursor_up, cuu1] string capability is the up one line.
            /// </summary>
            CursorUp = 19,

            /// <summary>
            /// The cursor_visible [cursor_visible, cvvis] string capability is the make cursor very visible.
            /// </summary>
            CursorVisible = 20,

            /// <summary>
            /// The delete_character [delete_character, dch1] string capability is the delete character p.
            /// </summary>
            DeleteCharacter = 21,

            /// <summary>
            /// The delete_line [delete_line, dl1] string capability is the delete line p.
            /// </summary>
            DeleteLine = 22,

            /// <summary>
            /// The dis_status_line [dis_status_line, dsl] string capability is the disable status line.
            /// </summary>
            DisStatusLine = 23,

            /// <summary>
            /// The down_half_line [down_half_line, hd] string capability is the half a line down.
            /// </summary>
            DownHalfLine = 24,

            /// <summary>
            /// The enter_alt_charset_mode [enter_alt_charset_mode, smacs] string capability is the start alternate character set p.
            /// </summary>
            EnterAltCharsetMode = 25,

            /// <summary>
            /// The enter_blink_mode [enter_blink_mode, blink] string capability is the turn on blinking.
            /// </summary>
            EnterBlinkMode = 26,

            /// <summary>
            /// The enter_bold_mode [enter_bold_mode, bold] string capability is the turn on bold extra bright mode.
            /// </summary>
            EnterBoldMode = 27,

            /// <summary>
            /// The enter_ca_mode [enter_ca_mode, smcup] string capability is the string to start programs using cup.
            /// </summary>
            EnterCaMode = 28,

            /// <summary>
            /// The enter_delete_mode [enter_delete_mode, smdc] string capability is the enter delete mode.
            /// </summary>
            EnterDeleteMode = 29,

            /// <summary>
            /// The enter_dim_mode [enter_dim_mode, dim] string capability is the turn on half bright mode.
            /// </summary>
            EnterDimMode = 30,

            /// <summary>
            /// The enter_insert_mode [enter_insert_mode, smir] string capability is the enter insert mode.
            /// </summary>
            EnterInsertMode = 31,

            /// <summary>
            /// The enter_secure_mode [enter_secure_mode, invis] string capability is the turn on blank mode characters invisible.
            /// </summary>
            EnterSecureMode = 32,

            /// <summary>
            /// The enter_protected_mode [enter_protected_mode, prot] string capability is the turn on protected mode.
            /// </summary>
            EnterProtectedMode = 33,

            /// <summary>
            /// The enter_reverse_mode [enter_reverse_mode, rev] string capability is the turn on reverse video mode.
            /// </summary>
            EnterReverseMode = 34,

            /// <summary>
            /// The enter_standout_mode [enter_standout_mode, smso] string capability is the begin standout mode.
            /// </summary>
            EnterStandoutMode = 35,

            /// <summary>
            /// The enter_underline_mode [enter_underline_mode, smul] string capability is the begin underline mode.
            /// </summary>
            EnterUnderlineMode = 36,

            /// <summary>
            /// The erase_chars [erase_chars, ech] string capability is the erase 1 characters p.
            /// </summary>
            EraseChars = 37,

            /// <summary>
            /// The exit_alt_charset_mode [exit_alt_charset_mode, rmacs] string capability is the end alternate character set p.
            /// </summary>
            ExitAltCharsetMode = 38,

            /// <summary>
            /// The exit_attribute_mode [exit_attribute_mode, sgr0] string capability is the turn off all attributes.
            /// </summary>
            ExitAttributeMode = 39,

            /// <summary>
            /// The exit_ca_mode [exit_ca_mode, rmcup] string capability is the strings to end programs using cup.
            /// </summary>
            ExitCaMode = 40,

            /// <summary>
            /// The exit_delete_mode [exit_delete_mode, rmdc] string capability is the end delete mode.
            /// </summary>
            ExitDeleteMode = 41,

            /// <summary>
            /// The exit_insert_mode [exit_insert_mode, rmir] string capability is the exit insert mode.
            /// </summary>
            ExitInsertMode = 42,

            /// <summary>
            /// The exit_standout_mode [exit_standout_mode, rmso] string capability is the exit standout mode.
            /// </summary>
            ExitStandoutMode = 43,

            /// <summary>
            /// The exit_underline_mode [exit_underline_mode, rmul] string capability is the exit underline mode.
            /// </summary>
            ExitUnderlineMode = 44,

            /// <summary>
            /// The flash_screen [flash_screen, flash] string capability is the visible bell may not move cursor.
            /// </summary>
            FlashScreen = 45,

            /// <summary>
            /// The form_feed [form_feed, ff] string capability is the hardcopy terminal page eject p.
            /// </summary>
            FormFeed = 46,

            /// <summary>
            /// The from_status_line [from_status_line, fsl] string capability is the return from status line.
            /// </summary>
            FromStatusLine = 47,

            /// <summary>
            /// The init_1string [init_1string, is1] string capability is the initialization string.
            /// </summary>
            Init1string = 48,

            /// <summary>
            /// The init_2string [init_2string, is2] string capability is the initialization string.
            /// </summary>
            Init2string = 49,

            /// <summary>
            /// The init_3string [init_3string, is3] string capability is the initialization string.
            /// </summary>
            Init3string = 50,

            /// <summary>
            /// The init_file [init_file, if] string capability is the name of initialization file.
            /// </summary>
            InitFile = 51,

            /// <summary>
            /// The insert_character [insert_character, ich1] string capability is the insert character p.
            /// </summary>
            InsertCharacter = 52,

            /// <summary>
            /// The insert_line [insert_line, il1] string capability is the insert line p.
            /// </summary>
            InsertLine = 53,

            /// <summary>
            /// The insert_padding [insert_padding, ip] string capability is the insert padding after inserted character.
            /// </summary>
            InsertPadding = 54,

            /// <summary>
            /// The key_backspace [key_backspace, kbs] string capability is the backspace key.
            /// </summary>
            KeyBackspace = 55,

            /// <summary>
            /// The key_catab [key_catab, ktbc] string capability is the clear all tabs key.
            /// </summary>
            KeyCatab = 56,

            /// <summary>
            /// The key_clear [key_clear, kclr] string capability is the clear screen or erase key.
            /// </summary>
            KeyClear = 57,

            /// <summary>
            /// The key_ctab [key_ctab, kctab] string capability is the clear tab key.
            /// </summary>
            KeyCtab = 58,

            /// <summary>
            /// The key_dc [key_dc, kdch1] string capability is the delete character key.
            /// </summary>
            KeyDc = 59,

            /// <summary>
            /// The key_dl [key_dl, kdl1] string capability is the delete line key.
            /// </summary>
            KeyDl = 60,

            /// <summary>
            /// The key_down [key_down, kcud1] string capability is the down arrow key.
            /// </summary>
            KeyDown = 61,

            /// <summary>
            /// The key_eic [key_eic, krmir] string capability is the sent by rmir or smir in insert mode.
            /// </summary>
            KeyEic = 62,

            /// <summary>
            /// The key_eol [key_eol, kel] string capability is the clear to end of line key.
            /// </summary>
            KeyEol = 63,

            /// <summary>
            /// The key_eos [key_eos, ked] string capability is the clear to end of screen key.
            /// </summary>
            KeyEos = 64,

            /// <summary>
            /// The key_f0 [key_f0, kf0] string capability is the f 0 function key.
            /// </summary>
            KeyF0 = 65,

            /// <summary>
            /// The key_f1 [key_f1, kf1] string capability is the f 1 function key.
            /// </summary>
            KeyF1 = 66,

            /// <summary>
            /// The key_f10 [key_f10, kf10] string capability is the f 10 function key.
            /// </summary>
            KeyF10 = 67,

            /// <summary>
            /// The key_f2 [key_f2, kf2] string capability is the f 2 function key.
            /// </summary>
            KeyF2 = 68,

            /// <summary>
            /// The key_f3 [key_f3, kf3] string capability is the f 3 function key.
            /// </summary>
            KeyF3 = 69,

            /// <summary>
            /// The key_f4 [key_f4, kf4] string capability is the f 4 function key.
            /// </summary>
            KeyF4 = 70,

            /// <summary>
            /// The key_f5 [key_f5, kf5] string capability is the f 5 function key.
            /// </summary>
            KeyF5 = 71,

            /// <summary>
            /// The key_f6 [key_f6, kf6] string capability is the f 6 function key.
            /// </summary>
            KeyF6 = 72,

            /// <summary>
            /// The key_f7 [key_f7, kf7] string capability is the f 7 function key.
            /// </summary>
            KeyF7 = 73,

            /// <summary>
            /// The key_f8 [key_f8, kf8] string capability is the f 8 function key.
            /// </summary>
            KeyF8 = 74,

            /// <summary>
            /// The key_f9 [key_f9, kf9] string capability is the f 9 function key.
            /// </summary>
            KeyF9 = 75,

            /// <summary>
            /// The key_home [key_home, khome] string capability is the home key.
            /// </summary>
            KeyHome = 76,

            /// <summary>
            /// The key_ic [key_ic, kich1] string capability is the insert character key.
            /// </summary>
            KeyIc = 77,

            /// <summary>
            /// The key_il [key_il, kil1] string capability is the insert line key.
            /// </summary>
            KeyIl = 78,

            /// <summary>
            /// The key_left [key_left, kcub1] string capability is the left arrow key.
            /// </summary>
            KeyLeft = 79,

            /// <summary>
            /// The key_ll [key_ll, kll] string capability is the lower left key (home down).
            /// </summary>
            KeyLl = 80,

            /// <summary>
            /// The key_npage [key_npage, knp] string capability is the next page key.
            /// </summary>
            KeyNpage = 81,

            /// <summary>
            /// The key_ppage [key_ppage, kpp] string capability is the previous page key.
            /// </summary>
            KeyPpage = 82,

            /// <summary>
            /// The key_right [key_right, kcuf1] string capability is the right arrow key.
            /// </summary>
            KeyRight = 83,

            /// <summary>
            /// The key_sf [key_sf, kind] string capability is the scroll forward key.
            /// </summary>
            KeySf = 84,

            /// <summary>
            /// The key_sr [key_sr, kri] string capability is the scroll backward key.
            /// </summary>
            KeySr = 85,

            /// <summary>
            /// The key_stab [key_stab, khts] string capability is the set tab key.
            /// </summary>
            KeyStab = 86,

            /// <summary>
            /// The key_up [key_up, kcuu1] string capability is the up arrow key.
            /// </summary>
            KeyUp = 87,

            /// <summary>
            /// The keypad_local [keypad_local, rmkx] string capability is the leave 'keyboard transmit' mode.
            /// </summary>
            KeypadLocal = 88,

            /// <summary>
            /// The keypad_xmit [keypad_xmit, smkx] string capability is the enter 'keyboard transmit' mode.
            /// </summary>
            KeypadXmit = 89,

            /// <summary>
            /// The lab_f0 [lab_f0, lf0] string capability is the label on function key f 0 if not f 0.
            /// </summary>
            LabF0 = 90,

            /// <summary>
            /// The lab_f1 [lab_f1, lf1] string capability is the label on function key f 1 if not f 1.
            /// </summary>
            LabF1 = 91,

            /// <summary>
            /// The lab_f10 [lab_f10, lf10] string capability is the label on function key f 10 if not f 10.
            /// </summary>
            LabF10 = 92,

            /// <summary>
            /// The lab_f2 [lab_f2, lf2] string capability is the label on function key f 2 if not f 2.
            /// </summary>
            LabF2 = 93,

            /// <summary>
            /// The lab_f3 [lab_f3, lf3] string capability is the label on function key f 3 if not f 3.
            /// </summary>
            LabF3 = 94,

            /// <summary>
            /// The lab_f4 [lab_f4, lf4] string capability is the label on function key f 4 if not f 4.
            /// </summary>
            LabF4 = 95,

            /// <summary>
            /// The lab_f5 [lab_f5, lf5] string capability is the label on function key f 5 if not f 5.
            /// </summary>
            LabF5 = 96,

            /// <summary>
            /// The lab_f6 [lab_f6, lf6] string capability is the label on function key f 6 if not f 6.
            /// </summary>
            LabF6 = 97,

            /// <summary>
            /// The lab_f7 [lab_f7, lf7] string capability is the label on function key f 7 if not f 7.
            /// </summary>
            LabF7 = 98,

            /// <summary>
            /// The lab_f8 [lab_f8, lf8] string capability is the label on function key f 8 if not f 8.
            /// </summary>
            LabF8 = 99,

            /// <summary>
            /// The lab_f9 [lab_f9, lf9] string capability is the label on function key f 9 if not f 9.
            /// </summary>
            LabF9 = 100,

            /// <summary>
            /// The meta_off [meta_off, rmm] string capability is the turn off meta mode.
            /// </summary>
            MetaOff = 101,

            /// <summary>
            /// The meta_on [meta_on, smm] string capability is the turn on meta mode (8th bit on).
            /// </summary>
            MetaOn = 102,

            /// <summary>
            /// The newline [newline, nel] string capability is the newline behave like cr followed by lf.
            /// </summary>
            Newline = 103,

            /// <summary>
            /// The pad_char [pad_char, pad] string capability is the padding char instead of null.
            /// </summary>
            PadChar = 104,

            /// <summary>
            /// The parm_dch [parm_dch, dch] string capability is the delete 1 characters p.
            /// </summary>
            ParmDch = 105,

            /// <summary>
            /// The parm_delete_line [parm_delete_line, dl] string capability is the delete 1 lines p.
            /// </summary>
            ParmDeleteLine = 106,

            /// <summary>
            /// The parm_down_cursor [parm_down_cursor, cud] string capability is the down 1 lines p.
            /// </summary>
            ParmDownCursor = 107,

            /// <summary>
            /// The parm_ich [parm_ich, ich] string capability is the insert 1 characters p.
            /// </summary>
            ParmIch = 108,

            /// <summary>
            /// The parm_index [parm_index, indn] string capability is the scroll forward 1 lines p.
            /// </summary>
            ParmIndex = 109,

            /// <summary>
            /// The parm_insert_line [parm_insert_line, il] string capability is the insert 1 lines p.
            /// </summary>
            ParmInsertLine = 110,

            /// <summary>
            /// The parm_left_cursor [parm_left_cursor, cub] string capability is the move 1 characters to the left p.
            /// </summary>
            ParmLeftCursor = 111,

            /// <summary>
            /// The parm_right_cursor [parm_right_cursor, cuf] string capability is the move 1 characters to the right p.
            /// </summary>
            ParmRightCursor = 112,

            /// <summary>
            /// The parm_rindex [parm_rindex, rin] string capability is the scroll back 1 lines p.
            /// </summary>
            ParmRindex = 113,

            /// <summary>
            /// The parm_up_cursor [parm_up_cursor, cuu] string capability is the up 1 lines p.
            /// </summary>
            ParmUpCursor = 114,

            /// <summary>
            /// The pkey_key [pkey_key, pfkey] string capability is the program function key 1 to type string 2.
            /// </summary>
            PkeyKey = 115,

            /// <summary>
            /// The pkey_local [pkey_local, pfloc] string capability is the program function key 1 to execute string 2.
            /// </summary>
            PkeyLocal = 116,

            /// <summary>
            /// The pkey_xmit [pkey_xmit, pfx] string capability is the program function key 1 to transmit string 2.
            /// </summary>
            PkeyXmit = 117,

            /// <summary>
            /// The print_screen [print_screen, mc0] string capability is the print contents of screen.
            /// </summary>
            PrintScreen = 118,

            /// <summary>
            /// The prtr_off [prtr_off, mc4] string capability is the turn off printer.
            /// </summary>
            PrtrOff = 119,

            /// <summary>
            /// The prtr_on [prtr_on, mc5] string capability is the turn on printer.
            /// </summary>
            PrtrOn = 120,

            /// <summary>
            /// The repeat_char [repeat_char, rep] string capability is the repeat char 1 2 times p.
            /// </summary>
            RepeatChar = 121,

            /// <summary>
            /// The reset_1string [reset_1string, rs1] string capability is the reset string.
            /// </summary>
            Reset1string = 122,

            /// <summary>
            /// The reset_2string [reset_2string, rs2] string capability is the reset string.
            /// </summary>
            Reset2string = 123,

            /// <summary>
            /// The reset_3string [reset_3string, rs3] string capability is the reset string.
            /// </summary>
            Reset3string = 124,

            /// <summary>
            /// The reset_file [reset_file, rf] string capability is the name of reset file.
            /// </summary>
            ResetFile = 125,

            /// <summary>
            /// The restore_cursor [restore_cursor, rc] string capability is the restore cursor to position of last save cursor.
            /// </summary>
            RestoreCursor = 126,

            /// <summary>
            /// The row_address [row_address, vpa] string capability is the vertical position 1 absolute p.
            /// </summary>
            RowAddress = 127,

            /// <summary>
            /// The save_cursor [save_cursor, sc] string capability is the save current cursor position p.
            /// </summary>
            SaveCursor = 128,

            /// <summary>
            /// The scroll_forward [scroll_forward, ind] string capability is the scroll text up p.
            /// </summary>
            ScrollForward = 129,

            /// <summary>
            /// The scroll_reverse [scroll_reverse, ri] string capability is the scroll text down p.
            /// </summary>
            ScrollReverse = 130,

            /// <summary>
            /// The set_attributes [set_attributes, sgr] string capability is the define video attributes #1 #9 (pg9).
            /// </summary>
            SetAttributes = 131,

            /// <summary>
            /// The set_tab [set_tab, hts] string capability is the set a tab in every row current columns.
            /// </summary>
            SetTab = 132,

            /// <summary>
            /// The set_window [set_window, wind] string capability is the current window is lines #1 #2 cols #3 #4.
            /// </summary>
            SetWindow = 133,

            /// <summary>
            /// The tab [tab, ht] string capability is the tab to next 8 space hardware tab stop.
            /// </summary>
            Tab = 134,

            /// <summary>
            /// The to_status_line [to_status_line, tsl] string capability is the move to status line column 1.
            /// </summary>
            ToStatusLine = 135,

            /// <summary>
            /// The underline_char [underline_char, uc] string capability is the underline char and move past it.
            /// </summary>
            UnderlineChar = 136,

            /// <summary>
            /// The up_half_line [up_half_line, hu] string capability is the half a line up.
            /// </summary>
            UpHalfLine = 137,

            /// <summary>
            /// The init_prog [init_prog, iprog] string capability is the path name of program for initialization.
            /// </summary>
            InitProg = 138,

            /// <summary>
            /// The key_a1 [key_a1, ka1] string capability is the upper left of keypad.
            /// </summary>
            KeyA1 = 139,

            /// <summary>
            /// The key_a3 [key_a3, ka3] string capability is the upper right of keypad.
            /// </summary>
            KeyA3 = 140,

            /// <summary>
            /// The key_b2 [key_b2, kb2] string capability is the center of keypad.
            /// </summary>
            KeyB2 = 141,

            /// <summary>
            /// The key_c1 [key_c1, kc1] string capability is the lower left of keypad.
            /// </summary>
            KeyC1 = 142,

            /// <summary>
            /// The key_c3 [key_c3, kc3] string capability is the lower right of keypad.
            /// </summary>
            KeyC3 = 143,

            /// <summary>
            /// The prtr_non [prtr_non, mc5p] string capability is the turn on printer for 1 bytes.
            /// </summary>
            PrtrNon = 144,

            /// <summary>
            /// The char_padding [char_padding, rmp] string capability is the like ip but when in insert mode.
            /// </summary>
            CharPadding = 145,

            /// <summary>
            /// The acs_chars [acs_chars, acsc] string capability is the graphics charset pairs based on vt 100.
            /// </summary>
            AcsChars = 146,

            /// <summary>
            /// The plab_norm [plab_norm, pln] string capability is the program label 1 to show string 2.
            /// </summary>
            PlabNorm = 147,

            /// <summary>
            /// The key_btab [key_btab, kcbt] string capability is the back tab key.
            /// </summary>
            KeyBtab = 148,

            /// <summary>
            /// The enter_xon_mode [enter_xon_mode, smxon] string capability is the turn on xon xoff handshaking.
            /// </summary>
            EnterXonMode = 149,

            /// <summary>
            /// The exit_xon_mode [exit_xon_mode, rmxon] string capability is the turn off xon xoff handshaking.
            /// </summary>
            ExitXonMode = 150,

            /// <summary>
            /// The enter_am_mode [enter_am_mode, smam] string capability is the turn on automatic margins.
            /// </summary>
            EnterAmMode = 151,

            /// <summary>
            /// The exit_am_mode [exit_am_mode, rmam] string capability is the turn off automatic margins.
            /// </summary>
            ExitAmMode = 152,

            /// <summary>
            /// The xon_character [xon_character, xonc] string capability is the xon character.
            /// </summary>
            XonCharacter = 153,

            /// <summary>
            /// The xoff_character [xoff_character, xoffc] string capability is the xoff character.
            /// </summary>
            XoffCharacter = 154,

            /// <summary>
            /// The ena_acs [ena_acs, enacs] string capability is the enable alternate char set.
            /// </summary>
            EnaAcs = 155,

            /// <summary>
            /// The label_on [label_on, smln] string capability is the turn on soft labels.
            /// </summary>
            LabelOn = 156,

            /// <summary>
            /// The label_off [label_off, rmln] string capability is the turn off soft labels.
            /// </summary>
            LabelOff = 157,

            /// <summary>
            /// The key_beg [key_beg, kbeg] string capability is the begin key.
            /// </summary>
            KeyBeg = 158,

            /// <summary>
            /// The key_cancel [key_cancel, kcan] string capability is the cancel key.
            /// </summary>
            KeyCancel = 159,

            /// <summary>
            /// The key_close [key_close, kclo] string capability is the close key.
            /// </summary>
            KeyClose = 160,

            /// <summary>
            /// The key_command [key_command, kcmd] string capability is the command key.
            /// </summary>
            KeyCommand = 161,

            /// <summary>
            /// The key_copy [key_copy, kcpy] string capability is the copy key.
            /// </summary>
            KeyCopy = 162,

            /// <summary>
            /// The key_create [key_create, kcrt] string capability is the create key.
            /// </summary>
            KeyCreate = 163,

            /// <summary>
            /// The key_end [key_end, kend] string capability is the end key.
            /// </summary>
            KeyEnd = 164,

            /// <summary>
            /// The key_enter [key_enter, kent] string capability is the enter send key.
            /// </summary>
            KeyEnter = 165,

            /// <summary>
            /// The key_exit [key_exit, kext] string capability is the exit key.
            /// </summary>
            KeyExit = 166,

            /// <summary>
            /// The key_find [key_find, kfnd] string capability is the find key.
            /// </summary>
            KeyFind = 167,

            /// <summary>
            /// The key_help [key_help, khlp] string capability is the help key.
            /// </summary>
            KeyHelp = 168,

            /// <summary>
            /// The key_mark [key_mark, kmrk] string capability is the mark key.
            /// </summary>
            KeyMark = 169,

            /// <summary>
            /// The key_message [key_message, kmsg] string capability is the message key.
            /// </summary>
            KeyMessage = 170,

            /// <summary>
            /// The key_move [key_move, kmov] string capability is the move key.
            /// </summary>
            KeyMove = 171,

            /// <summary>
            /// The key_next [key_next, knxt] string capability is the next key.
            /// </summary>
            KeyNext = 172,

            /// <summary>
            /// The key_open [key_open, kopn] string capability is the open key.
            /// </summary>
            KeyOpen = 173,

            /// <summary>
            /// The key_options [key_options, kopt] string capability is the options key.
            /// </summary>
            KeyOptions = 174,

            /// <summary>
            /// The key_previous [key_previous, kprv] string capability is the previous key.
            /// </summary>
            KeyPrevious = 175,

            /// <summary>
            /// The key_print [key_print, kprt] string capability is the print key.
            /// </summary>
            KeyPrint = 176,

            /// <summary>
            /// The key_redo [key_redo, krdo] string capability is the redo key.
            /// </summary>
            KeyRedo = 177,

            /// <summary>
            /// The key_reference [key_reference, kref] string capability is the reference key.
            /// </summary>
            KeyReference = 178,

            /// <summary>
            /// The key_refresh [key_refresh, krfr] string capability is the refresh key.
            /// </summary>
            KeyRefresh = 179,

            /// <summary>
            /// The key_replace [key_replace, krpl] string capability is the replace key.
            /// </summary>
            KeyReplace = 180,

            /// <summary>
            /// The key_restart [key_restart, krst] string capability is the restart key.
            /// </summary>
            KeyRestart = 181,

            /// <summary>
            /// The key_resume [key_resume, kres] string capability is the resume key.
            /// </summary>
            KeyResume = 182,

            /// <summary>
            /// The key_save [key_save, ksav] string capability is the save key.
            /// </summary>
            KeySave = 183,

            /// <summary>
            /// The key_suspend [key_suspend, kspd] string capability is the suspend key.
            /// </summary>
            KeySuspend = 184,

            /// <summary>
            /// The key_undo [key_undo, kund] string capability is the undo key.
            /// </summary>
            KeyUndo = 185,

            /// <summary>
            /// The key_sbeg [key_sbeg, kBEG] string capability is the shifted begin key.
            /// </summary>
            KeySbeg = 186,

            /// <summary>
            /// The key_scancel [key_scancel, kCAN] string capability is the shifted cancel key.
            /// </summary>
            KeyScancel = 187,

            /// <summary>
            /// The key_scommand [key_scommand, kCMD] string capability is the shifted command key.
            /// </summary>
            KeyScommand = 188,

            /// <summary>
            /// The key_scopy [key_scopy, kCPY] string capability is the shifted copy key.
            /// </summary>
            KeyScopy = 189,

            /// <summary>
            /// The key_screate [key_screate, kCRT] string capability is the shifted create key.
            /// </summary>
            KeyScreate = 190,

            /// <summary>
            /// The key_sdc [key_sdc, kDC] string capability is the shifted delete character key.
            /// </summary>
            KeySdc = 191,

            /// <summary>
            /// The key_sdl [key_sdl, kDL] string capability is the shifted delete line key.
            /// </summary>
            KeySdl = 192,

            /// <summary>
            /// The key_select [key_select, kslt] string capability is the select key.
            /// </summary>
            KeySelect = 193,

            /// <summary>
            /// The key_send [key_send, kEND] string capability is the shifted end key.
            /// </summary>
            KeySend = 194,

            /// <summary>
            /// The key_seol [key_seol, kEOL] string capability is the shifted clear to end of line key.
            /// </summary>
            KeySeol = 195,

            /// <summary>
            /// The key_sexit [key_sexit, kEXT] string capability is the shifted exit key.
            /// </summary>
            KeySexit = 196,

            /// <summary>
            /// The key_sfind [key_sfind, kFND] string capability is the shifted find key.
            /// </summary>
            KeySfind = 197,

            /// <summary>
            /// The key_shelp [key_shelp, kHLP] string capability is the shifted help key.
            /// </summary>
            KeyShelp = 198,

            /// <summary>
            /// The key_shome [key_shome, kHOM] string capability is the shifted home key.
            /// </summary>
            KeyShome = 199,

            /// <summary>
            /// The key_sic [key_sic, kIC] string capability is the shifted insert character key.
            /// </summary>
            KeySic = 200,

            /// <summary>
            /// The key_sleft [key_sleft, kLFT] string capability is the shifted left arrow key.
            /// </summary>
            KeySleft = 201,

            /// <summary>
            /// The key_smessage [key_smessage, kMSG] string capability is the shifted message key.
            /// </summary>
            KeySmessage = 202,

            /// <summary>
            /// The key_smove [key_smove, kMOV] string capability is the shifted move key.
            /// </summary>
            KeySmove = 203,

            /// <summary>
            /// The key_snext [key_snext, kNXT] string capability is the shifted next key.
            /// </summary>
            KeySnext = 204,

            /// <summary>
            /// The key_soptions [key_soptions, kOPT] string capability is the shifted options key.
            /// </summary>
            KeySoptions = 205,

            /// <summary>
            /// The key_sprevious [key_sprevious, kPRV] string capability is the shifted previous key.
            /// </summary>
            KeySprevious = 206,

            /// <summary>
            /// The key_sprint [key_sprint, kPRT] string capability is the shifted print key.
            /// </summary>
            KeySprint = 207,

            /// <summary>
            /// The key_sredo [key_sredo, kRDO] string capability is the shifted redo key.
            /// </summary>
            KeySredo = 208,

            /// <summary>
            /// The key_sreplace [key_sreplace, kRPL] string capability is the shifted replace key.
            /// </summary>
            KeySreplace = 209,

            /// <summary>
            /// The key_sright [key_sright, kRIT] string capability is the shifted right arrow key.
            /// </summary>
            KeySright = 210,

            /// <summary>
            /// The key_srsume [key_srsume, kRES] string capability is the shifted resume key.
            /// </summary>
            KeySrsume = 211,

            /// <summary>
            /// The key_ssave [key_ssave, kSAV] string capability is the shifted save key.
            /// </summary>
            KeySsave = 212,

            /// <summary>
            /// The key_ssuspend [key_ssuspend, kSPD] string capability is the shifted suspend key.
            /// </summary>
            KeySsuspend = 213,

            /// <summary>
            /// The key_sundo [key_sundo, kUND] string capability is the shifted undo key.
            /// </summary>
            KeySundo = 214,

            /// <summary>
            /// The req_for_input [req_for_input, rfi] string capability is the send next input char for ptys.
            /// </summary>
            ReqForInput = 215,

            /// <summary>
            /// The key_f11 [key_f11, kf11] string capability is the f 11 function key.
            /// </summary>
            KeyF11 = 216,

            /// <summary>
            /// The key_f12 [key_f12, kf12] string capability is the f 12 function key.
            /// </summary>
            KeyF12 = 217,

            /// <summary>
            /// The key_f13 [key_f13, kf13] string capability is the f 13 function key.
            /// </summary>
            KeyF13 = 218,

            /// <summary>
            /// The key_f14 [key_f14, kf14] string capability is the f 14 function key.
            /// </summary>
            KeyF14 = 219,

            /// <summary>
            /// The key_f15 [key_f15, kf15] string capability is the f 15 function key.
            /// </summary>
            KeyF15 = 220,

            /// <summary>
            /// The key_f16 [key_f16, kf16] string capability is the f 16 function key.
            /// </summary>
            KeyF16 = 221,

            /// <summary>
            /// The key_f17 [key_f17, kf17] string capability is the f 17 function key.
            /// </summary>
            KeyF17 = 222,

            /// <summary>
            /// The key_f18 [key_f18, kf18] string capability is the f 18 function key.
            /// </summary>
            KeyF18 = 223,

            /// <summary>
            /// The key_f19 [key_f19, kf19] string capability is the f 19 function key.
            /// </summary>
            KeyF19 = 224,

            /// <summary>
            /// The key_f20 [key_f20, kf20] string capability is the f 20 function key.
            /// </summary>
            KeyF20 = 225,

            /// <summary>
            /// The key_f21 [key_f21, kf21] string capability is the f 21 function key.
            /// </summary>
            KeyF21 = 226,

            /// <summary>
            /// The key_f22 [key_f22, kf22] string capability is the f 22 function key.
            /// </summary>
            KeyF22 = 227,

            /// <summary>
            /// The key_f23 [key_f23, kf23] string capability is the f 23 function key.
            /// </summary>
            KeyF23 = 228,

            /// <summary>
            /// The key_f24 [key_f24, kf24] string capability is the f 24 function key.
            /// </summary>
            KeyF24 = 229,

            /// <summary>
            /// The key_f25 [key_f25, kf25] string capability is the f 25 function key.
            /// </summary>
            KeyF25 = 230,

            /// <summary>
            /// The key_f26 [key_f26, kf26] string capability is the f 26 function key.
            /// </summary>
            KeyF26 = 231,

            /// <summary>
            /// The key_f27 [key_f27, kf27] string capability is the f 27 function key.
            /// </summary>
            KeyF27 = 232,

            /// <summary>
            /// The key_f28 [key_f28, kf28] string capability is the f 28 function key.
            /// </summary>
            KeyF28 = 233,

            /// <summary>
            /// The key_f29 [key_f29, kf29] string capability is the f 29 function key.
            /// </summary>
            KeyF29 = 234,

            /// <summary>
            /// The key_f30 [key_f30, kf30] string capability is the f 30 function key.
            /// </summary>
            KeyF30 = 235,

            /// <summary>
            /// The key_f31 [key_f31, kf31] string capability is the f 31 function key.
            /// </summary>
            KeyF31 = 236,

            /// <summary>
            /// The key_f32 [key_f32, kf32] string capability is the f 32 function key.
            /// </summary>
            KeyF32 = 237,

            /// <summary>
            /// The key_f33 [key_f33, kf33] string capability is the f 33 function key.
            /// </summary>
            KeyF33 = 238,

            /// <summary>
            /// The key_f34 [key_f34, kf34] string capability is the f 34 function key.
            /// </summary>
            KeyF34 = 239,

            /// <summary>
            /// The key_f35 [key_f35, kf35] string capability is the f 35 function key.
            /// </summary>
            KeyF35 = 240,

            /// <summary>
            /// The key_f36 [key_f36, kf36] string capability is the f 36 function key.
            /// </summary>
            KeyF36 = 241,

            /// <summary>
            /// The key_f37 [key_f37, kf37] string capability is the f 37 function key.
            /// </summary>
            KeyF37 = 242,

            /// <summary>
            /// The key_f38 [key_f38, kf38] string capability is the f 38 function key.
            /// </summary>
            KeyF38 = 243,

            /// <summary>
            /// The key_f39 [key_f39, kf39] string capability is the f 39 function key.
            /// </summary>
            KeyF39 = 244,

            /// <summary>
            /// The key_f40 [key_f40, kf40] string capability is the f 40 function key.
            /// </summary>
            KeyF40 = 245,

            /// <summary>
            /// The key_f41 [key_f41, kf41] string capability is the f 41 function key.
            /// </summary>
            KeyF41 = 246,

            /// <summary>
            /// The key_f42 [key_f42, kf42] string capability is the f 42 function key.
            /// </summary>
            KeyF42 = 247,

            /// <summary>
            /// The key_f43 [key_f43, kf43] string capability is the f 43 function key.
            /// </summary>
            KeyF43 = 248,

            /// <summary>
            /// The key_f44 [key_f44, kf44] string capability is the f 44 function key.
            /// </summary>
            KeyF44 = 249,

            /// <summary>
            /// The key_f45 [key_f45, kf45] string capability is the f 45 function key.
            /// </summary>
            KeyF45 = 250,

            /// <summary>
            /// The key_f46 [key_f46, kf46] string capability is the f 46 function key.
            /// </summary>
            KeyF46 = 251,

            /// <summary>
            /// The key_f47 [key_f47, kf47] string capability is the f 47 function key.
            /// </summary>
            KeyF47 = 252,

            /// <summary>
            /// The key_f48 [key_f48, kf48] string capability is the f 48 function key.
            /// </summary>
            KeyF48 = 253,

            /// <summary>
            /// The key_f49 [key_f49, kf49] string capability is the f 49 function key.
            /// </summary>
            KeyF49 = 254,

            /// <summary>
            /// The key_f50 [key_f50, kf50] string capability is the f 50 function key.
            /// </summary>
            KeyF50 = 255,

            /// <summary>
            /// The key_f51 [key_f51, kf51] string capability is the f 51 function key.
            /// </summary>
            KeyF51 = 256,

            /// <summary>
            /// The key_f52 [key_f52, kf52] string capability is the f 52 function key.
            /// </summary>
            KeyF52 = 257,

            /// <summary>
            /// The key_f53 [key_f53, kf53] string capability is the f 53 function key.
            /// </summary>
            KeyF53 = 258,

            /// <summary>
            /// The key_f54 [key_f54, kf54] string capability is the f 54 function key.
            /// </summary>
            KeyF54 = 259,

            /// <summary>
            /// The key_f55 [key_f55, kf55] string capability is the f 55 function key.
            /// </summary>
            KeyF55 = 260,

            /// <summary>
            /// The key_f56 [key_f56, kf56] string capability is the f 56 function key.
            /// </summary>
            KeyF56 = 261,

            /// <summary>
            /// The key_f57 [key_f57, kf57] string capability is the f 57 function key.
            /// </summary>
            KeyF57 = 262,

            /// <summary>
            /// The key_f58 [key_f58, kf58] string capability is the f 58 function key.
            /// </summary>
            KeyF58 = 263,

            /// <summary>
            /// The key_f59 [key_f59, kf59] string capability is the f 59 function key.
            /// </summary>
            KeyF59 = 264,

            /// <summary>
            /// The key_f60 [key_f60, kf60] string capability is the f 60 function key.
            /// </summary>
            KeyF60 = 265,

            /// <summary>
            /// The key_f61 [key_f61, kf61] string capability is the f 61 function key.
            /// </summary>
            KeyF61 = 266,

            /// <summary>
            /// The key_f62 [key_f62, kf62] string capability is the f 62 function key.
            /// </summary>
            KeyF62 = 267,

            /// <summary>
            /// The key_f63 [key_f63, kf63] string capability is the f 63 function key.
            /// </summary>
            KeyF63 = 268,

            /// <summary>
            /// The clr_bol [clr_bol, el1] string capability is the clear to beginning of line.
            /// </summary>
            ClrBol = 269,

            /// <summary>
            /// The clear_margins [clear_margins, mgc] string capability is the clear right and left soft margins.
            /// </summary>
            ClearMargins = 270,

            /// <summary>
            /// The set_left_margin [set_left_margin, smgl] string capability is the set left soft margin at current column.
            /// </summary>
            SetLeftMargin = 271,

            /// <summary>
            /// The set_right_margin [set_right_margin, smgr] string capability is the set right soft margin at current column.
            /// </summary>
            SetRightMargin = 272,

            /// <summary>
            /// The label_format [label_format, fln] string capability is the label format.
            /// </summary>
            LabelFormat = 273,

            /// <summary>
            /// The set_clock [set_clock, sclk] string capability is the set clock 1 hrs 2 mins 3 secs.
            /// </summary>
            SetClock = 274,

            /// <summary>
            /// The display_clock [display_clock, dclk] string capability is the display clock.
            /// </summary>
            DisplayClock = 275,

            /// <summary>
            /// The remove_clock [remove_clock, rmclk] string capability is the remove clock.
            /// </summary>
            RemoveClock = 276,

            /// <summary>
            /// The create_window [create_window, cwin] string capability is the define a window 1 from 2 3 to 4 5.
            /// </summary>
            CreateWindow = 277,

            /// <summary>
            /// The goto_window [goto_window, wingo] string capability is the go to window 1.
            /// </summary>
            GotoWindow = 278,

            /// <summary>
            /// The hangup [hangup, hup] string capability is the hang up phone.
            /// </summary>
            Hangup = 279,

            /// <summary>
            /// The dial_phone [dial_phone, dial] string capability is the dial number 1.
            /// </summary>
            DialPhone = 280,

            /// <summary>
            /// The quick_dial [quick_dial, qdial] string capability is the dial number 1 without checking.
            /// </summary>
            QuickDial = 281,

            /// <summary>
            /// The tone [tone, tone] string capability is the select touch tone dialing.
            /// </summary>
            Tone = 282,

            /// <summary>
            /// The pulse [pulse, pulse] string capability is the select pulse dialing.
            /// </summary>
            Pulse = 283,

            /// <summary>
            /// The flash_hook [flash_hook, hook] string capability is the flash switch hook.
            /// </summary>
            FlashHook = 284,

            /// <summary>
            /// The fixed_pause [fixed_pause, pause] string capability is the pause for 2 3 seconds.
            /// </summary>
            FixedPause = 285,

            /// <summary>
            /// The wait_tone [wait_tone, wait] string capability is the wait for dial tone.
            /// </summary>
            WaitTone = 286,

            /// <summary>
            /// The user0 [user0, u0] string capability is the user string 0.
            /// </summary>
            User0 = 287,

            /// <summary>
            /// The user1 [user1, u1] string capability is the user string 1.
            /// </summary>
            User1 = 288,

            /// <summary>
            /// The user2 [user2, u2] string capability is the user string 2.
            /// </summary>
            User2 = 289,

            /// <summary>
            /// The user3 [user3, u3] string capability is the user string 3.
            /// </summary>
            User3 = 290,

            /// <summary>
            /// The user4 [user4, u4] string capability is the user string 4.
            /// </summary>
            User4 = 291,

            /// <summary>
            /// The user5 [user5, u5] string capability is the user string 5.
            /// </summary>
            User5 = 292,

            /// <summary>
            /// The user6 [user6, u6] string capability is the user string 6.
            /// </summary>
            User6 = 293,

            /// <summary>
            /// The user7 [user7, u7] string capability is the user string 7.
            /// </summary>
            User7 = 294,

            /// <summary>
            /// The user8 [user8, u8] string capability is the user string 8.
            /// </summary>
            User8 = 295,

            /// <summary>
            /// The user9 [user9, u9] string capability is the user string 9.
            /// </summary>
            User9 = 296,

            /// <summary>
            /// The orig_pair [orig_pair, op] string capability is the set default pair to its original value.
            /// </summary>
            OrigPair = 297,

            /// <summary>
            /// The orig_colors [orig_colors, oc] string capability is the set all color pairs to the original ones.
            /// </summary>
            OrigColors = 298,

            /// <summary>
            /// The initialize_color [initialize_color, initc] string capability is the initialize color 1 to 2 3 4.
            /// </summary>
            InitializeColor = 299,

            /// <summary>
            /// The initialize_pair [initialize_pair, initp] string capability is the initialize color pair 1 to fg 2 3 4 bg 5 6 7.
            /// </summary>
            InitializePair = 300,

            /// <summary>
            /// The set_color_pair [set_color_pair, scp] string capability is the set current color pair to 1.
            /// </summary>
            SetColorPair = 301,

            /// <summary>
            /// The set_foreground [set_foreground, setf] string capability is the set foreground color 1.
            /// </summary>
            SetForeground = 302,

            /// <summary>
            /// The set_background [set_background, setb] string capability is the set background color 1.
            /// </summary>
            SetBackground = 303,

            /// <summary>
            /// The change_char_pitch [change_char_pitch, cpi] string capability is the change number of characters per inch to 1.
            /// </summary>
            ChangeCharPitch = 304,

            /// <summary>
            /// The change_line_pitch [change_line_pitch, lpi] string capability is the change number of lines per inch to 1.
            /// </summary>
            ChangeLinePitch = 305,

            /// <summary>
            /// The change_res_horz [change_res_horz, chr] string capability is the change horizontal resolution to 1.
            /// </summary>
            ChangeResHorz = 306,

            /// <summary>
            /// The change_res_vert [change_res_vert, cvr] string capability is the change vertical resolution to 1.
            /// </summary>
            ChangeResVert = 307,

            /// <summary>
            /// The define_char [define_char, defc] string capability is the define a character 1 2 dots wide descender 3.
            /// </summary>
            DefineChar = 308,

            /// <summary>
            /// The enter_doublewide_mode [enter_doublewide_mode, swidm] string capability is the enter double wide mode.
            /// </summary>
            EnterDoublewideMode = 309,

            /// <summary>
            /// The enter_draft_quality [enter_draft_quality, sdrfq] string capability is the enter draft quality mode.
            /// </summary>
            EnterDraftQuality = 310,

            /// <summary>
            /// The enter_italics_mode [enter_italics_mode, sitm] string capability is the enter italic mode.
            /// </summary>
            EnterItalicsMode = 311,

            /// <summary>
            /// The enter_leftward_mode [enter_leftward_mode, slm] string capability is the start leftward carriage motion.
            /// </summary>
            EnterLeftwardMode = 312,

            /// <summary>
            /// The enter_micro_mode [enter_micro_mode, smicm] string capability is the start micro motion mode.
            /// </summary>
            EnterMicroMode = 313,

            /// <summary>
            /// The enter_near_letter_quality [enter_near_letter_quality, snlq] string capability is the enter nlq mode.
            /// </summary>
            EnterNearLetterQuality = 314,

            /// <summary>
            /// The enter_normal_quality [enter_normal_quality, snrmq] string capability is the enter normal quality mode.
            /// </summary>
            EnterNormalQuality = 315,

            /// <summary>
            /// The enter_shadow_mode [enter_shadow_mode, sshm] string capability is the enter shadow print mode.
            /// </summary>
            EnterShadowMode = 316,

            /// <summary>
            /// The enter_subscript_mode [enter_subscript_mode, ssubm] string capability is the enter subscript mode.
            /// </summary>
            EnterSubscriptMode = 317,

            /// <summary>
            /// The enter_superscript_mode [enter_superscript_mode, ssupm] string capability is the enter superscript mode.
            /// </summary>
            EnterSuperscriptMode = 318,

            /// <summary>
            /// The enter_upward_mode [enter_upward_mode, sum] string capability is the start upward carriage motion.
            /// </summary>
            EnterUpwardMode = 319,

            /// <summary>
            /// The exit_doublewide_mode [exit_doublewide_mode, rwidm] string capability is the end double wide mode.
            /// </summary>
            ExitDoublewideMode = 320,

            /// <summary>
            /// The exit_italics_mode [exit_italics_mode, ritm] string capability is the end italic mode.
            /// </summary>
            ExitItalicsMode = 321,

            /// <summary>
            /// The exit_leftward_mode [exit_leftward_mode, rlm] string capability is the end left motion mode.
            /// </summary>
            ExitLeftwardMode = 322,

            /// <summary>
            /// The exit_micro_mode [exit_micro_mode, rmicm] string capability is the end micro motion mode.
            /// </summary>
            ExitMicroMode = 323,

            /// <summary>
            /// The exit_shadow_mode [exit_shadow_mode, rshm] string capability is the end shadow print mode.
            /// </summary>
            ExitShadowMode = 324,

            /// <summary>
            /// The exit_subscript_mode [exit_subscript_mode, rsubm] string capability is the end subscript mode.
            /// </summary>
            ExitSubscriptMode = 325,

            /// <summary>
            /// The exit_superscript_mode [exit_superscript_mode, rsupm] string capability is the end superscript mode.
            /// </summary>
            ExitSuperscriptMode = 326,

            /// <summary>
            /// The exit_upward_mode [exit_upward_mode, rum] string capability is the end reverse character motion.
            /// </summary>
            ExitUpwardMode = 327,

            /// <summary>
            /// The micro_column_address [micro_column_address, mhpa] string capability is the like column address in micro mode.
            /// </summary>
            MicroColumnAddress = 328,

            /// <summary>
            /// The micro_down [micro_down, mcud1] string capability is the like cursor down in micro mode.
            /// </summary>
            MicroDown = 329,

            /// <summary>
            /// The micro_left [micro_left, mcub1] string capability is the like cursor left in micro mode.
            /// </summary>
            MicroLeft = 330,

            /// <summary>
            /// The micro_right [micro_right, mcuf1] string capability is the like cursor right in micro mode.
            /// </summary>
            MicroRight = 331,

            /// <summary>
            /// The micro_row_address [micro_row_address, mvpa] string capability is the like row address #1 in micro mode.
            /// </summary>
            MicroRowAddress = 332,

            /// <summary>
            /// The micro_up [micro_up, mcuu1] string capability is the like cursor up in micro mode.
            /// </summary>
            MicroUp = 333,

            /// <summary>
            /// The order_of_pins [order_of_pins, porder] string capability is the match software bits to print head pins.
            /// </summary>
            OrderOfPins = 334,

            /// <summary>
            /// The parm_down_micro [parm_down_micro, mcud] string capability is the like parm down cursor in micro mode.
            /// </summary>
            ParmDownMicro = 335,

            /// <summary>
            /// The parm_left_micro [parm_left_micro, mcub] string capability is the like parm left cursor in micro mode.
            /// </summary>
            ParmLeftMicro = 336,

            /// <summary>
            /// The parm_right_micro [parm_right_micro, mcuf] string capability is the like parm right cursor in micro mode.
            /// </summary>
            ParmRightMicro = 337,

            /// <summary>
            /// The parm_up_micro [parm_up_micro, mcuu] string capability is the like parm up cursor in micro mode.
            /// </summary>
            ParmUpMicro = 338,

            /// <summary>
            /// The select_char_set [select_char_set, scs] string capability is the select character set 1.
            /// </summary>
            SelectCharSet = 339,

            /// <summary>
            /// The set_bottom_margin [set_bottom_margin, smgb] string capability is the set bottom margin at current line.
            /// </summary>
            SetBottomMargin = 340,

            /// <summary>
            /// The set_bottom_margin_parm [set_bottom_margin_parm, smgbp] string capability is the set bottom margin at line 1 or if smgtp is not given 2 lines from bottom.
            /// </summary>
            SetBottomMarginParm = 341,

            /// <summary>
            /// The set_left_margin_parm [set_left_margin_parm, smglp] string capability is the set left right margin at column 1.
            /// </summary>
            SetLeftMarginParm = 342,

            /// <summary>
            /// The set_right_margin_parm [set_right_margin_parm, smgrp] string capability is the set right margin at column 1.
            /// </summary>
            SetRightMarginParm = 343,

            /// <summary>
            /// The set_top_margin [set_top_margin, smgt] string capability is the set top margin at current line.
            /// </summary>
            SetTopMargin = 344,

            /// <summary>
            /// The set_top_margin_parm [set_top_margin_parm, smgtp] string capability is the set top bottom margin at row 1.
            /// </summary>
            SetTopMarginParm = 345,

            /// <summary>
            /// The start_bit_image [start_bit_image, sbim] string capability is the start printing bit image graphics.
            /// </summary>
            StartBitImage = 346,

            /// <summary>
            /// The start_char_set_def [start_char_set_def, scsd] string capability is the start character set definition 1 with 2 characters in the set.
            /// </summary>
            StartCharSetDef = 347,

            /// <summary>
            /// The stop_bit_image [stop_bit_image, rbim] string capability is the stop printing bit image graphics.
            /// </summary>
            StopBitImage = 348,

            /// <summary>
            /// The stop_char_set_def [stop_char_set_def, rcsd] string capability is the end definition of character set 1.
            /// </summary>
            StopCharSetDef = 349,

            /// <summary>
            /// The subscript_characters [subscript_characters, subcs] string capability is the list of subscriptable characters.
            /// </summary>
            SubscriptCharacters = 350,

            /// <summary>
            /// The superscript_characters [superscript_characters, supcs] string capability is the list of superscriptable characters.
            /// </summary>
            SuperscriptCharacters = 351,

            /// <summary>
            /// The these_cause_cr [these_cause_cr, docr] string capability is the printing any of these characters causes cr.
            /// </summary>
            TheseCauseCr = 352,

            /// <summary>
            /// The zero_motion [zero_motion, zerom] string capability is the no motion for subsequent character.
            /// </summary>
            ZeroMotion = 353,

            /// <summary>
            /// The char_set_names [char_set_names, csnm] string capability is the produce 1 th item from list of character set names.
            /// </summary>
            CharSetNames = 354,

            /// <summary>
            /// The key_mouse [key_mouse, kmous] string capability is the mouse event has occurred.
            /// </summary>
            KeyMouse = 355,

            /// <summary>
            /// The mouse_info [mouse_info, minfo] string capability is the mouse status information.
            /// </summary>
            MouseInfo = 356,

            /// <summary>
            /// The req_mouse_pos [req_mouse_pos, reqmp] string capability is the request mouse position.
            /// </summary>
            ReqMousePos = 357,

            /// <summary>
            /// The get_mouse [get_mouse, getm] string capability is the curses should get button events parameter 1 not documented.
            /// </summary>
            GetMouse = 358,

            /// <summary>
            /// The set_a_foreground [set_a_foreground, setaf] string capability is the set foreground color to 1 using ansi escape.
            /// </summary>
            SetAForeground = 359,

            /// <summary>
            /// The set_a_background [set_a_background, setab] string capability is the set background color to 1 using ansi escape.
            /// </summary>
            SetABackground = 360,

            /// <summary>
            /// The pkey_plab [pkey_plab, pfxl] string capability is the program function key 1 to type string 2 and show string 3.
            /// </summary>
            PkeyPlab = 361,

            /// <summary>
            /// The device_type [device_type, devt] string capability is the indicate language codeset support.
            /// </summary>
            DeviceType = 362,

            /// <summary>
            /// The code_set_init [code_set_init, csin] string capability is the init sequence for multiple codesets.
            /// </summary>
            CodeSetInit = 363,

            /// <summary>
            /// The set0_des_seq [set0_des_seq, s0ds] string capability is the shift to codeset 0 euc set 0 ascii.
            /// </summary>
            Set0DesSeq = 364,

            /// <summary>
            /// The set1_des_seq [set1_des_seq, s1ds] string capability is the shift to codeset 1.
            /// </summary>
            Set1DesSeq = 365,

            /// <summary>
            /// The set2_des_seq [set2_des_seq, s2ds] string capability is the shift to codeset 2.
            /// </summary>
            Set2DesSeq = 366,

            /// <summary>
            /// The set3_des_seq [set3_des_seq, s3ds] string capability is the shift to codeset 3.
            /// </summary>
            Set3DesSeq = 367,

            /// <summary>
            /// The set_lr_margin [set_lr_margin, smglr] string capability is the set both left and right margins to 1 2 ml is not in bsd termcap.
            /// </summary>
            SetLrMargin = 368,

            /// <summary>
            /// The set_tb_margin [set_tb_margin, smgtb] string capability is the sets both top and bottom margins to 1 2.
            /// </summary>
            SetTbMargin = 369,

            /// <summary>
            /// The bit_image_repeat [bit_image_repeat, birep] string capability is the repeat bit image cell 1 2 times.
            /// </summary>
            BitImageRepeat = 370,

            /// <summary>
            /// The bit_image_newline [bit_image_newline, binel] string capability is the move to next row of the bit image.
            /// </summary>
            BitImageNewline = 371,

            /// <summary>
            /// The bit_image_carriage_return [bit_image_carriage_return, bicr] string capability is the move to beginning of same row.
            /// </summary>
            BitImageCarriageReturn = 372,

            /// <summary>
            /// The color_names [color_names, colornm] string capability is the give name for color 1.
            /// </summary>
            ColorNames = 373,

            /// <summary>
            /// The define_bit_image_region [define_bit_image_region, defbi] string capability is the define rectangular bit image region.
            /// </summary>
            DefineBitImageRegion = 374,

            /// <summary>
            /// The end_bit_image_region [end_bit_image_region, endbi] string capability is the end a bit image region.
            /// </summary>
            EndBitImageRegion = 375,

            /// <summary>
            /// The set_color_band [set_color_band, setcolor] string capability is the change to ribbon color 1.
            /// </summary>
            SetColorBand = 376,

            /// <summary>
            /// The set_page_length [set_page_length, slines] string capability is the set page length to 1 lines.
            /// </summary>
            SetPageLength = 377,

            /// <summary>
            /// The display_pc_char [display_pc_char, dispc] string capability is the display pc character 1.
            /// </summary>
            DisplayPcChar = 378,

            /// <summary>
            /// The enter_pc_charset_mode [enter_pc_charset_mode, smpch] string capability is the enter pc character display mode.
            /// </summary>
            EnterPcCharsetMode = 379,

            /// <summary>
            /// The exit_pc_charset_mode [exit_pc_charset_mode, rmpch] string capability is the exit pc character display mode.
            /// </summary>
            ExitPcCharsetMode = 380,

            /// <summary>
            /// The enter_scancode_mode [enter_scancode_mode, smsc] string capability is the enter pc scancode mode.
            /// </summary>
            EnterScancodeMode = 381,

            /// <summary>
            /// The exit_scancode_mode [exit_scancode_mode, rmsc] string capability is the exit pc scancode mode.
            /// </summary>
            ExitScancodeMode = 382,

            /// <summary>
            /// The pc_term_options [pc_term_options, pctrm] string capability is the pc terminal options.
            /// </summary>
            PcTermOptions = 383,

            /// <summary>
            /// The scancode_escape [scancode_escape, scesc] string capability is the escape for scancode emulation.
            /// </summary>
            ScancodeEscape = 384,

            /// <summary>
            /// The alt_scancode_esc [alt_scancode_esc, scesa] string capability is the alternate escape for scancode emulation.
            /// </summary>
            AltScancodeEsc = 385,

            /// <summary>
            /// The enter_horizontal_hl_mode [enter_horizontal_hl_mode, ehhlm] string capability is the enter horizontal highlight mode.
            /// </summary>
            EnterHorizontalHlMode = 386,

            /// <summary>
            /// The enter_left_hl_mode [enter_left_hl_mode, elhlm] string capability is the enter left highlight mode.
            /// </summary>
            EnterLeftHlMode = 387,

            /// <summary>
            /// The enter_low_hl_mode [enter_low_hl_mode, elohlm] string capability is the enter low highlight mode.
            /// </summary>
            EnterLowHlMode = 388,

            /// <summary>
            /// The enter_right_hl_mode [enter_right_hl_mode, erhlm] string capability is the enter right highlight mode.
            /// </summary>
            EnterRightHlMode = 389,

            /// <summary>
            /// The enter_top_hl_mode [enter_top_hl_mode, ethlm] string capability is the enter top highlight mode.
            /// </summary>
            EnterTopHlMode = 390,

            /// <summary>
            /// The enter_vertical_hl_mode [enter_vertical_hl_mode, evhlm] string capability is the enter vertical highlight mode.
            /// </summary>
            EnterVerticalHlMode = 391,

            /// <summary>
            /// The set_a_attributes [set_a_attributes, sgr1] string capability is the define second set of video attributes #1 #6.
            /// </summary>
            SetAAttributes = 392,

            /// <summary>
            /// The set_pglen_inch [set_pglen_inch, slength] string capability is the set page length to 1 hundredth of an inch some implementations use s l for termcap.
            /// </summary>
            SetPglenInch = 393,

            /// <summary>
            /// The termcap_init2 [termcap_init2, OTi2] string capability is the secondary initialization string.
            /// </summary>
            TermcapInit2 = 394,

            /// <summary>
            /// The termcap_reset [termcap_reset, OTrs] string capability is the terminal reset string.
            /// </summary>
            TermcapReset = 395,

            /// <summary>
            /// The linefeed_if_not_lf [linefeed_if_not_lf, OTnl] string capability is the use to move down.
            /// </summary>
            LinefeedIfNotLf = 396,

            /// <summary>
            /// The backspace_if_not_bs [backspace_if_not_bs, OTbc] string capability is the move left if not h.
            /// </summary>
            BackspaceIfNotBs = 397,

            /// <summary>
            /// The other_non_function_keys [other_non_function_keys, OTko] string capability is the list of self mapped keycaps.
            /// </summary>
            OtherNonFunctionKeys = 398,

            /// <summary>
            /// The arrow_key_map [arrow_key_map, OTma] string capability is the map motion keys for vi version 2.
            /// </summary>
            ArrowKeyMap = 399,

            /// <summary>
            /// The acs_ulcorner [acs_ulcorner, OTG2] string capability is the single upper left.
            /// </summary>
            AcsUlcorner = 400,

            /// <summary>
            /// The acs_llcorner [acs_llcorner, OTG3] string capability is the single lower left.
            /// </summary>
            AcsLlcorner = 401,

            /// <summary>
            /// The acs_urcorner [acs_urcorner, OTG1] string capability is the single upper right.
            /// </summary>
            AcsUrcorner = 402,

            /// <summary>
            /// The acs_lrcorner [acs_lrcorner, OTG4] string capability is the single lower right.
            /// </summary>
            AcsLrcorner = 403,

            /// <summary>
            /// The acs_ltee [acs_ltee, OTGR] string capability is the tee pointing right.
            /// </summary>
            AcsLtee = 404,

            /// <summary>
            /// The acs_rtee [acs_rtee, OTGL] string capability is the tee pointing left.
            /// </summary>
            AcsRtee = 405,

            /// <summary>
            /// The acs_btee [acs_btee, OTGU] string capability is the tee pointing up.
            /// </summary>
            AcsBtee = 406,

            /// <summary>
            /// The acs_ttee [acs_ttee, OTGD] string capability is the tee pointing down.
            /// </summary>
            AcsTtee = 407,

            /// <summary>
            /// The acs_hline [acs_hline, OTGH] string capability is the single horizontal line.
            /// </summary>
            AcsHline = 408,

            /// <summary>
            /// The acs_vline [acs_vline, OTGV] string capability is the single vertical line.
            /// </summary>
            AcsVline = 409,

            /// <summary>
            /// The acs_plus [acs_plus, OTGC] string capability is the single intersection.
            /// </summary>
            AcsPlus = 410,

            /// <summary>
            /// The memory_lock [memory_lock, meml] string capability is the lock memory above cursor.
            /// </summary>
            MemoryLock = 411,

            /// <summary>
            /// The memory_unlock [memory_unlock, memu] string capability is the unlock memory.
            /// </summary>
            MemoryUnlock = 412,

            /// <summary>
            /// The box_chars_1 [box_chars_1, box1] string capability is the box characters primary set.
            /// </summary>
            BoxChars1 = 413,
        }
    }
}